# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae0301859383f1b69a56f6a2dc7f745dcc5dfae6774cb3385f5f423d1b5ceeaa6a45490405839ca900a521c0bd518a419e8a65ecd4a8d11701884cc435ef1cdc

test:
  secret_key_base: 428aac18a9495fb77398f34b78ec13aabfc16c5a851744aec227102c43ff5cb11ebbb2c2afbe8b73ee0706d69c92760bdfbd93a0d09a4678c3d4e1be90d38913

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
